### PR TITLE
chore: add yardenshoham to contributors

### PR DESCRIPTION
**Pull request by YardenShoham**
**What**:

Added my self to .all-contributorsrc.

**Why**:

I was asked by @gnapse in #130.

**How**:

Simply added another JSON to .all-contributorsrc.
**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [ ] Updated Type Definitions N/A
- [X] Ready to be merged

### CODE REVIEW

**Comment by gnapse** [comment]
Can you please also update [this file](https://github.com/testing-library/jest-dom/blob/master/.github/PULL_REQUEST_TEMPLATE.md) to include a new entry in the checklist saying "Added myself to the contributors list". If you can't no worries, I can take care of it too.

**Comment by gnapse** [comment]
Also, there's something missing here. I'm pretty sure that after you add yourself there's some command to be run to update the README so you also appear on it. That's auto generated by some command. Maybe @kentcdodds can help me refresh my mind about this as I do not recall how it's done.

**Comment by afontcu** [comment]
Hi!

I don't think it should done manually – instead, an admin should mention `all-contributors` as in here: https://github.com/testing-library/dom-testing-library/pull/344#issuecomment-528423771

**Comment by YardenShoham** [comment]
@gnapse I added the changes you requested. I had to google how to do it and found [this tool](https://github.com/all-contributors/all-contributors-cli). I agree with @afontcu, the bot should be used - it was created for this purpose.

**Comment by gnapse** [comment]
Ok nice, I did not know that bot existed. I tried it out in #130 and it's working, it created #132 so I think we can close this PR and will merge that one. Sorry to having made you waste a bit of time on this @YardenShoham. Thanks @afontcu for pointing this out to us.

**Pull request closed without merging**
