### PR TITLE
fix: upgrade `@adobe/css-tools` to `4.3.1` to address vulnerability

### PR DESCRIPTION
**Pull request by justinbaltazar**
**What**:
This PR bumps the `@adobe/css-tools` dependency to 4.3.1

**Why**:
There is an existing advisory on version `4.3.0`:
https://github.com/advisories/GHSA-hpx4-r86g-5jrg

**How**:
Updated `package.json`.

**Checklist**:
- [X] Documentation
- [X] Tests
- [X] Updated Type Definitions
- [X] Ready to be merged

### CODE REVIEW

**Review by MiladSadeghi — APPROVED** [review]

**Comment by lritter79** [comment]
@nickmccurdy

**Comment by jgoz** [comment]
I don't see the point of this change. The existing dependency range will allow package consumers to update the transitive dependency version via `npm audit fix` or equivalent with other package managers. What am I missing?

**Comment by lritter79** [comment]
@jgoz I think it's worth adding this change to ensure that consumers of this package are secure since 4.3.0 has a vulnerability, and it would be courteous to just bump the version up and keep this package reliable.

**Review by nickmccurdy — APPROVED** [review]

**Comment by nickmccurdy** [comment]
Merging since it's just a patch release which shouldn't have breaking changes.

**Comment by justinbaltazar** [comment]
Thanks all!

**Pull request merged**
