### PR TITLE
feat: Drop support for Node 12

### PR DESCRIPTION
**Pull request by nickmccurdy**
**What**: Don't test with node 10, 12, or 15

**Why**: Node 10, 12, and 15 reached EOL so let's free up some CI resources.

**How**: Remove 10, 12, and 15 from node test matrix.

**Checklist**:

- ~[ ]~ Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [x] Tests
- ~[ ]~ Typescript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Review by gnapse — APPROVED** [review]

**Comment by gnapse** [comment]
@nickmccurdy what's pending for us to merge this?

**Comment by nickmccurdy** [comment]
This should be safe to merge now, as Node 10 and 15 are no longer supported.

**Comment by nickmccurdy** [comment]
@MichaelDeBoey Should we set engines to `>=12` while we're at it or does that need to be in a separate PR since it's a breaking change?

**Comment by nickmccurdy** [comment]
**Update:** I've also updated `engines`, so you should publish this as a breaking change.

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by IanVS** [comment]
@gnapse are you waiting a little longer to also drop node 12 support?  That's coming pretty soon (less than a month, 2022-04-30).

**Comment by nickmccurdy** [comment]
Node 12 support has ended, so I've also removed it.

**Comment by nickmccurdy** [comment]
It would be great to merge this soon if possible. Two users have already gotten confused by #473.

**Comment by IanVS** [comment]
There's also https://github.com/testing-library/jest-dom/pull/438 waiting to be released on the `next` branch, maybe in a beta?

**Comment by nickmccurdy** [comment]
I noticed, that's why I didn't change the base to `main`.

**Comment by IanVS** [comment]
There is https://github.com/testing-library/jest-dom/pull/453 that I can pick back up if there's a chance it will be merged/released.  I kind of gave up hope on a breaking release, until now.

**Comment by nickmccurdy** [comment]
@IanVS Let me know if I can help with anything there. I think we might want another breaking change in this release too: https://github.com/testing-library/jest-dom/pull/472

**Comment by IanVS** [comment]
@nickmccurdy I've updated https://github.com/testing-library/jest-dom/pull/453 if you'd like to give it a review.  Thanks for the nudge.

**Comment by IanVS** [comment]
I believe this can be closed now, since #511 dropped support for node < 14.

**Pull request closed without merging**
