### PR TITLE
fix: add vitest import when extending vitest matchers

### PR DESCRIPTION
**Pull request by InfiniteXyy**
**What**:
https://github.com/testing-library/jest-dom/issues/645
Fix a vitest typing issue when using global mode

**Why**:
If there is no import of "vitest" in the whole project (for example, vitest is in globalMode), the type merging might not work.

**How**:
By adding an import of "vitest" when extending the matcher type

reference: https://vitest.dev/guide/extending-matchers.html

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Updated Type Definitions
- [ ] Ready to be merged

### CODE REVIEW

**Review by G-Rath — APPROVED** [review]
sorry about this! I think the fix here is right

cc @gnapse

**Review by gnapse — APPROVED** [review]

**Comment by gnapse** [comment]
@all-contributors please add @InfiniteXyy for code, bug

**Comment by dnafication** [comment]
This is causing issues like #662. Is there a workaround for this?

**Comment by dnafication** [comment]
The issue occurs on triggering tests using vitest. Just running npx vitest
results in the error

**Comment by dnafication** [comment]
Turns out the issue was due to a leftover import in my vitest.setup.ts for cleaning up after each test. I still see it in the [setup instruction for svelte](https://testing-library.com/docs/svelte-testing-library/setup#:~:text=Add%20a%20vitest%2Dsetup.js%20file%20to%20optionally%20set%20up%20%40testing%2Dlibrary/jest%2Ddom%20expect%20matchers).

```js
import "@testing-library/jest-dom/vitest"
```

**Pull request merged**
