### PR TITLE
chore: Drop peerDependencies from package.json

### LINKED ISSUE #608: Is it possible to have a version not depending on jest, @jest/globals ?
### Describe the feature you'd like:

A version of this package that does not have jest / @jest/globals as peer dependencies. These dependencies are installed automatically by npm (in recent versions) and if you're using Vitest and not Jest, you still end up installing tons of jest-related dependencies.

Any advice on how this could get implemented? I'm willing to help btw :)

### PR DESCRIPTION
**Pull request by ddolcimascolo**
**What**:

Drop peerDependencies from package.json

**Why**:

See https://github.com/testing-library/jest-dom/issues/608 for the complete motivation, and discussion

Closes #608 

**How**:

Editing package.json

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [ ] Updated Type Definitions N/A
- [x] Ready to be merged

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
This is fine with me. I can't merge this though as I'm not an active maintainer.

**Review by gnapse — APPROVED** [review]

**Comment by gnapse** [comment]
@ddolcimascolo can you update your upstream `main` and rebase this on top, or merge the updated `main` onto your branch? This branch is out-of-date with the base branch, and that's a condition needed for this to be merged.

**Comment by ddolcimascolo** [comment]
> @ddolcimascolo can you update your upstream `main` and rebase this on top, or merge the updated `main` onto your branch? This branch is out-of-date with the base branch, and that's a condition needed for this to be merged.

Done

**Comment by ddolcimascolo** [comment]
Thx for the 👍, looking forward for a release!

**Comment by gnapse** [comment]
@all-contributors please add @ddolcimascolo for maintenance

**Pull request merged**
