### PR TITLE
Publish both esm and cjs

### LINKED ISSUE #437: Publish ES modules
### Describe the feature you'd like:

I am a maintainer of storybook-builder-vite, which allows storybook users to build their previews using vite, which works entirely in ESM.  Storybook recently also released [@storybook/jest](https://github.com/storybookjs/jest) and the latest release extends expect with jest-dom matchers.  However, since jest-dom is only published as commonjs, typescript needs to add a compatibility layer so that `import * as matchers from @testing-library/jest-dom/matchers;` can be used.  This is causing an issue, whereby a `default` is being included as well, causing expect to throw an error.  See https://github.com/storybookjs/jest/issues/15#issuecomment-1049045296 for the error description.   

To avoid the esm/cjs bundling problems, I'd like to request that jest-dom publish an esm version alongside cjs.  

### Suggested implementation:

I see that you're using `kcd-scripts build`, which also allows a `--bundle` flag that builds cjs, esm, umd, and umd.min bundles.  Alternatively, https://github.com/unjs/unbuild is a very simple build tool which can generate multiple targets.

### Describe alternatives you've considered:

I'm trying to troubleshoot the symptom of the esm->cjs namespace import to see if there's a way I can work around it in the storybook packages, but I think it would be nice if this package could publish esm anyway, especially now that jest itself is publishing es modules.

### Teachability, Documentation, Adoption, Migration Strategy:

I think as long as the `package.json` is updated correctly, there shouldn't be any user-facing changes needed.  That said, bundling the files as suggested above will cause problems if users are importing files directly from `node_modules/@testing-library/jest-dom/dist`.  If that's the case, and it's a use case that needs to be supported, then a different build process will be needed, but can still be accomplished.

### PR DESCRIPTION
**Pull request by IanVS**
**What**:

This publishes both es modules and commonjs in the bundle.  

**Why**:

Closes #437 

**How**:

I used rollup to generate the two sets of bundles.  I'm not doing any processing on either of them aside from what rollup does by default, mostly because I'm not sure what level of browser/node support this project follows.  It would be pretty straightforward to add https://www.npmjs.com/package/@rollup/plugin-babel or otherwise configure the output as needed.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Updated Type Definitions
- [ ] Ready to be merged
      

I haven't updated any documentation or tests, because I wanted to see if this was at all on the right track.

### CODE REVIEW

**Comment by IanVS** [comment]
To be safe, maybe this could be released along with https://github.com/testing-library/jest-dom/pull/379 in a major version bump.

**Comment by IanVS** [comment]
@gnapse I have tested in my own vite storybook app, by running `npm build`, and copying the `package.json` and `dist` over to my project's node_modules.  

I don't have a traditional jest project running in node to test the cjs build on, but the process would be the same.  

Perhaps you could publish an `alpha` or `beta` version, that people could test out?

**Comment by IanVS** [comment]
@gnapse do you still plan to release a beta version with this change?  Is there anything else you'd like me to do before you're comfortable with it?

**Comment by gnapse** [comment]
@IanVS sorry for the delay. I'm going to resume work on this tomorrow. I'll decide then if I go with a alpha or beta version first.

**Comment by yannbf** [comment]
Thank you all for doing this! I was wondering whether there are plans to release this in an alpha version somewhere?

Thank you <3

**Comment by IanVS** [comment]
Hi is there any plan to release this?  It's kind of a bummer that I put the work into it and there's still no way to use it.

**Comment by yannbf** [comment]
Hey @gnapse was this change ever included in a release?

**Comment by kasperpeulen** [comment]
Can this PR also be merged to main?

**Comment by IanVS** [comment]
It looks like the other changes that were in `next` were cherry-picked back to main and released, but not this one.  Does anyone have any information why?  It would be great to publish ESM, if at all possible.

**Comment by IanVS** [comment]
OK, I see now this needs to be reworked a bit based on the multiple export paths now supported for vitest, etc.  I'll open a new PR.

**Pull request merged**
