### PR TITLE
Updated jest Matchers namespace declaration

### PR DESCRIPTION
**Pull request by shadrech**
**What**:

Jest namespace extension was out of date. The Matchers interface only accepts one generics variable

**Why**:

Though its stated as being deprecated I find once this is updated and I import as mentioned in [docs](https://github.com/testing-library/jest-dom#usage) typings work as expected

### CODE REVIEW

**Comment by gnapse** [comment]
This seems to be at odds with #150. The change you're trying to introduce here is the exact opposite of that other PR. Can you read over that PR's description and the reasoning of why this was done? Because that one seem to suggest that what you want to introduce here is what's really out of date. Maybe we can involve the author of that PR in the discussion (@bopfer) as well as @jgoz who approved it.

**Comment by bopfer** [comment]
#150 was done to sync up with `@types/jest`.  This comment explains the reasoning: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39243#issuecomment-550512994

**Comment by jgoz** [comment]
Yeah, #150 introduced an implicit dependency upgrade to the latest Jest typings. I was worried this would happen (user upgrades to latest jest-dom, but not jest typings), but we don’t currently have a way to communicate this implicit dependency.

Maybe we could add `@types/jest` as an optional peer dep?

**Comment by gnapse** [comment]
> user upgrades to latest jest-dom, but not jest typings)

Not sure what to do about this then, since either state of affairs affect some people.

> Maybe we could add @types/jest as an optional peer dep?

Would that definitely solve the issue? Are there any downsides?

**Comment by jgoz** [comment]
> > user upgrades to latest jest-dom, but not jest typings)
> 
> Not sure what to do about this then, since either state of affairs affect some people.

I think it's simpler (for us) to always stay in sync with the latest Jest typings. My assumption is that people generally upgrade all jest-related packages together, including `jest-dom`.


> > Maybe we could add @types/jest as an optional peer dep?
> 
> Would that definitely solve the issue? Are there any downsides?

I wouldn't say it will "definitely solve" the issue since people can ignore peer dependency warnings, but it would at least provide some compatibility guidance for those using the typings.

**Comment by gnapse** [comment]
Nice, seems reasonable.

@shadrech can you change this PR following what's discussed above?

**Comment by shadrech** [comment]
Yh sure. Give me till the weekend and I'll work on it

**Comment by shadrech** [comment]
Done @gnapse . Sorry for forced push. I had merged my local master branch which had some other changes I had made. Let me know if my changes suffice 👍

**Comment by shadrech** [comment]
@jgoz Kindly review. Thanks

**Comment by gnapse** [comment]
@jgoz how does this fare under the light of our recent work to fix #123? (context: #175, #182 and DefinitelyTyped/DefinitelyTyped#37792).

**Comment by jgoz** [comment]
This can be closed. Once the types are published to DT, they will have `@types/jest` as a dependency.

**Pull request closed without merging**
