### PR TITLE
Update aria-query to 5.0.0

### LINKED ISSUE #413: Update aria-query to avoid babel runtime
### Describe the feature you'd like:

I'd like to suggest an update to aria-query@5.  They removed their usage of Map and Set, and by doing so, removed babel as runtime dependencies.  I'm currently struggling with one of the babel dependencies that is being brought in to my project via this package, and it could save disk space for other consumers who are not using babel as well.

### PR DESCRIPTION
**Pull request by IanVS**
**What**:

This updates the version of `aria-query` to 5.0.0.  

**Why**:

Closes #413.

**How**:

This is a breaking change in that Map and Set are no longer used.  But, the `roles` object that is returned has methods on it, including `.get()`, which is used in `roleSupportsChecked`.

The only update I made to the code is to remove the `Array.from()` call, since `roles.keys()` already returns an array now.

**Checklist**:

- [ ] Documentation N/A
- [X] Tests
- [ ] Updated Type Definitions N/A
- [X] Ready to be merged

### CODE REVIEW

**Comment by IanVS** [comment]
Hi, the corresponding PR was merged into dom-testing-library.  Would anyone like to take a look at this PR?  I think it's best if the versions stay in-sync.

**Comment by gnapse** [comment]
To confirm what you seem to say in the PR description: is this a breaking change to the outside world?

**Comment by IanVS** [comment]
I do not believe this is breaking, and a major release was not needed for dom-testing-library, see: https://github.com/testing-library/dom-testing-library/pull/1058#issuecomment-945597465

**Review by gnapse — APPROVED** [review]

**Comment by gnapse** [comment]
@all-contributors please add @IanVS for code

**Comment by IanVS** [comment]
Thanks @gnapse!

**Pull request merged**
