### PR TITLE
improve error messages for .toBeInTheDocument

### PR DESCRIPTION
**Pull request by kandros**
**What**:

Improve error messages for `.toBeInTheDocument`

**Why**:

The current error was hard to understand

**How**:

Give more context in the error message

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [ ] Updated Type Definitions N/A
- [X] Ready to be merged

---

### Before

`.toBeInTheDocument` 
Screenshot 2019-10-05 at 12 29 08

`not.toBeInTheDocument`
Screenshot 2019-10-05 at 12 28 05

### After

`.toBeInTheDocument` 
Screenshot 2019-10-05 at 12 18 15

`not.toBeInTheDocument`
Screenshot 2019-10-05 at 12 52 13

### CODE REVIEW

**Comment by gnapse** [comment]
@kandros I'll be merging this soon. It totally slipped off my mind, sorry for the long delay.

**Comment by gnapse** [comment]
Not sure why the build here is taking forever. Invoking @testing-library/core-maintainers in case someone there can chime in on what went wrong.

**Comment by kentcdodds** [comment]
I'm not sure. I wouldn't worry about it. Just merge if you're happy with the changes :)

**Pull request merged**
