### PR TITLE
Change urls to new location in testing-library org

### PR DESCRIPTION
**Pull request by gnapse**
**What**:

Change all URLs referencing the old location of this repo in github to the new location under the testing-library organization.

### CODE REVIEW

**Comment by gnapse** [comment]
However, it worries me that the CI status is still pending. Could it be related to the switch to the org?

**Comment by kentcdodds** [comment]
It could. I'm trying to make sure travis is working properly...

**Comment by kentcdodds** [comment]
Looks like it's here: https://travis-ci.org/testing-library/jest-dom

**Comment by kentcdodds** [comment]
I'm guessing it's just a transition thing and it'll work fine for future PRs/builds.

**Pull request merged**
