### PR TITLE
Add `toHaveErrorMessage` matcher

### PR DESCRIPTION
**Pull request by SevenOutman**
**What**:

feature: `.toHaveErrorMessage` matcher to check whether an invalid element has requested [error message](https://www.w3.org/TR/wai-aria/#aria-errormessage).

**Why**:

This PR is basically a replacement of the stale PR #258 which implements proposal #256. 

**How**:

Most implementation and tests are copied from the original PR with some modification to address testing issues. 

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Updated Type Definitions https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53505
- [x] Ready to be merged

### CODE REVIEW

**Review by gnapse — APPROVED** [review]
Thanks a lot for this. Very thorough implementation and tests. Thanks.

**Comment by gnapse** [comment]
@all-contributors please add @SevenOutman for code, test

**Comment by SevenOutman** [comment]
@kentcdodds I'd recommend using this matcher for testing form validation instead of `toHaveDescription` in your showcases. What do you think?

**Comment by kentcdodds** [comment]
Sounds great. What showcase are you referring to?

**Comment by SevenOutman** [comment]
> What showcase are you referring to?

I remember seeing several in Testing Javascript courses, but couldn't recall which exactly.

**Comment by kentcdodds** [comment]
I'll keep it in mind in the future! Thanks 👍

**Comment by ITenthusiasm** [comment]
Seeing this after the fact. :sweat_smile:

Just as a heads up @kentcdodds @SevenOutman, the `aria-errormessage` attribute [doesn't have Full Screen Reader support yet](https://a11ysupport.io/tech/aria/aria-errormessage_attribute). I was very sad to find this out. For instance, I can hear error messages on iOS, but not on MacOS -- as the provided link shows.

It seems that for right now, the recommended way of conveying error messages to users is still to use `aria-describedby`. But! There's much more support for `aria-errormessage` now than there used to be a year ago. I'm really hopeful/excited for full support to come through, as `aria-errormessage` could help with a lot of things.

In the meantime, any documentation or examples that use `aria-errormessage` might want to have some warnings attached with the aforementioned information.

**Pull request merged**
