### PR TITLE
chore: typo in to-have-attribute.js comment

### PR DESCRIPTION
**Pull request by YardenShoham**
**What**:

A typo is being corrected.

**Why**:

A typo should not exist in the comments.

**How**:

I fixed the typo and corrected the spelling.
Line 45: Asymettic matchers --> Asymmetric matchers

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [ ] Updated Type Definitions N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by YardenShoham** [comment]
Thanks for approving my contribution. Could I be added to the contributors so I'll appear in README.md?

**Comment by gnapse** [comment]
> Could I be added to the contributors so I'll appear in README.md?

Of course! I thought you weren't interested as this is something you could and should've added in your PR. I would've sworn that we had a checkbox for that in the PR template checklist so as to remind people. Would you mind contributing with that too?

**Comment by YardenShoham** [comment]
OK. On it.

**Comment by YardenShoham** [comment]
It's done. #131.

**Comment by gnapse** [comment]
@all-contributors please add @YardenShoham for docs

**Pull request merged**
